### ISSUE TITLE
 Could not open library '/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation

### ISSUE THREAD

**Issue by fedya** [EugenMayer/docker_registry_cli#10]
Linux localhost.localdomain 3.10.0-514.26.1.vz7.33.22 #1 SMP Sat Jul 29 14:57:34 MSK 2017 x86_64 x86_64 x86_64 GNU/Linux

Centos 7

```
[root@localhost ~]# docker_registry_cli --help
/usr/local/share/gems/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library '/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation': /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation: cannot open shared object file: No such file or directory (LoadError)
        from /usr/local/share/gems/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
        from /usr/local/share/gems/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
        from /usr/local/share/gems/gems/corefoundation-0.2.0/lib/corefoundation/base.rb:7:in `<module:CF>'
        from /usr/local/share/gems/gems/corefoundation-0.2.0/lib/corefoundation/base.rb:5:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/corefoundation-0.2.0/lib/corefoundation.rb:4:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/ruby-keychain-0.3.2/lib/keychain.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/docker_registry_cli-0.1.0/auth/TokenAuthService.rb:1:in `<top (required)>'
        from /usr/local/share/gems/gems/docker_registry_cli-0.1.0/requests/DockerRegistryRequest.rb:9:in `require_relative'
        from /usr/local/share/gems/gems/docker_registry_cli-0.1.0/requests/DockerRegistryRequest.rb:9:in `<top (required)>'
        from /usr/local/share/gems/gems/docker_registry_cli-0.1.0/commands/DockerRegistryCommand.rb:3:in `require_relative'
        from /usr/local/share/gems/gems/docker_registry_cli-0.1.0/commands/DockerRegistryCommand.rb:3:in `<top (required)>'
        from /usr/local/share/gems/gems/docker_registry_cli-0.1.0/bin/docker_registry_cli:7:in `require_relative'
        from /usr/local/share/gems/gems/docker_registry_cli-0.1.0/bin/docker_registry_cli:7:in `<top (required)>'
        from /usr/local/bin/docker_registry_cli:23:in `load'
        from /usr/local/bin/docker_registry_cli:23:in `<main>'
[root@localhost ~]# ^C

```

**Comment by fedya** [comment]
Well, i masked first line in /usr/local/share/gems/gems/docker_registry_cli-0.1.0/auth/TokenAuthService.rb 
and seems to be issue fixed.
