### ISSUE TITLE
Error while running on ubuntu

### ISSUE THREAD

**Issue by tdroenner** [EugenMayer/docker_registry_cli#4]
sudo docker_registry_cli --help
/var/lib/gems/1.9.1/gems/ffi-1.9.14/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library '/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation': /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation: cannot open shared object file: No such file or directory (LoadError)
        from /var/lib/gems/1.9.1/gems/ffi-1.9.14/lib/ffi/library.rb:100:in`map'
        from /var/lib/gems/1.9.1/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `ffi_lib'
        from /var/lib/gems/1.9.1/gems/corefoundation-0.2.0/lib/corefoundation/base.rb:7:in`module:CF'
        from /var/lib/gems/1.9.1/gems/corefoundation-0.2.0/lib/corefoundation/base.rb:5:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/corefoundation-0.2.0/lib/corefoundation.rb:4:in`<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /var/lib/gems/1.9.1/gems/ruby-keychain-0.3.2/lib/keychain.rb:2:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/docker_registry_cli-0.1.0/auth/TokenAuthService.rb:1:in`<top (required)>'
        from /var/lib/gems/1.9.1/gems/docker_registry_cli-0.1.0/requests/DockerRegistryRequest.rb:9:in `require_relative'
        from /var/lib/gems/1.9.1/gems/docker_registry_cli-0.1.0/requests/DockerRegistryRequest.rb:9:in`<top (required)>'
        from /var/lib/gems/1.9.1/gems/docker_registry_cli-0.1.0/commands/DockerRegistryCommand.rb:3:in `require_relative'
        from /var/lib/gems/1.9.1/gems/docker_registry_cli-0.1.0/commands/DockerRegistryCommand.rb:3:in`<top (required)>'
        from /var/lib/gems/1.9.1/gems/docker_registry_cli-0.1.0/bin/docker_registry_cli:7:in `require_relative'
        from /var/lib/gems/1.9.1/gems/docker_registry_cli-0.1.0/bin/docker_registry_cli:7:in`<top (required)>'
        from /usr/local/bin/docker_registry_cli:23:in `load'
        from /usr/local/bin/docker_registry_cli:23:in`<main>'

I guess CoreFoundation is MacOSX only. Is this dependency really needed?

**Comment by EugenMayer** [comment]
The problem is the credentials helper which is i mplemented dir OSX only, patches are welcome, i will most probably not work on this issue

**Comment by jdoose** [comment]
That's too bad, looks like a great tool!
Wouldn't it be possible to include the dependency only if the credentials helper is used?

**Comment by v3loc1rapt0r** [comment]
If you do not need a Token Auth then put # in the front of the first line in file:
docker_registry_cli-master/auth/TokenAuthService.rb
so it looks like:
#require 'keychain'
then everything works fine.

**Comment by attila123** [comment]
Finally run
[sudo] ./deploy_locally.sh
to deploy the modified version.
