### ISSUE TITLE
Does not appear to support private insecure registries

### ISSUE THREAD

**Issue by ghost** [EugenMayer/docker_registry_cli#9]
when attempting to run `docker_registry_cli list` against our internal private repo which has auth disabled and is using an invalid certificate, we see the following error:

```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/protocol.rb:44:in 'connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/protocol.rb:44:in 'ssl_socket_connect'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:948:in 'connect'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:887:in 'do_start'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:876:in 'start'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:1407:in 'request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/httparty-0.15.5/lib/httparty/request.rb:142:in 'perform'
	from /usr/local/lib/ruby/gems/2.4.0/gems/httparty-0.15.5/lib/httparty.rb:563:in 'perform_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/httparty-0.15.5/lib/httparty.rb:489:in 'get'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker_registry_cli-0.1.0/requests/DockerRegistryRequest.rb:72:in 'send_get_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker_registry_cli-0.1.0/commands/DockerRegistryCommand.rb:8:in 'list'
	from /usr/local/lib/ruby/gems/2.4.0/gems/docker_registry_cli-0.1.0/bin/docker_registry_cli:116:in '<top (required)>'
	from /usr/local/bin/docker_registry_cli:22:in 'load'
	from /usr/local/bin/docker_registry_cli:22:in '<main>'
```

Our ~/.docker_registry.yml looks like:
`domain: private-repo.ourcompany.com:5000`

This _appears_ to be an issue with the self-signed cert?

**Comment by EugenMayer** [comment]
import the self signed cert that way that ruby does not freak outi guess
